export const MODEL_SPECS = {
  name: "Kairo-10M",
  description: "A ~10.23M parameter decoder-only Transformer implemented completely from scratch.",
  architecture: "decoder-only Transformer",
  vocabulary: 16384,
  maxSeqLen: 2048,
  hiddenSize: 256,
  layers: 8,
  attentionHeads: 4,
  headDim: 64,
  ffnIntermediate: 640,
  normalization: "RMSNorm",
  normalizationEps: 1e-6,
  activation: "SwiGLU",
  positionalEncoding: "RoPE",
  attentionType: "causal multi-head self-attention",
  attentionBias: false,
  weightTying: true,
  parameters: "10.23M",
  parameterCount: 10230000,
} as const;

export const IMPLEMENTED_FEATURES = [
  "Configuration system",
  "Parameter counting",
  "RMSNorm",
  "Token embeddings",
  "RoPE",
  "SwiGLU",
  "Causal self-attention",
  "Transformer blocks",
  "Full Kairo model",
  "Weight-tied LM head",
  "Loss computation",
  "Tokenizer interface",
  "Test suite",
  "Model inspection",
  "Validation",
] as const;

export const ROADMAP_ITEMS = [
  { name: "Dataset downloader", status: "future" as const },
  { name: "Web crawler", status: "future" as const },
  { name: "Pretraining", status: "future" as const },
  { name: "Distributed training", status: "future" as const },
  { name: "RLHF", status: "future" as const },
  { name: "Instruction tuning", status: "future" as const },
  { name: "Chat UI", status: "future" as const },
  { name: "API server", status: "future" as const },
  { name: "Quantization", status: "future" as const },
  { name: "Speculative decoding", status: "future" as const },
  { name: "MoE", status: "future" as const },
  { name: "Multimodal inputs", status: "future" as const },
  { name: "Retrieval augmentation", status: "future" as const },
  { name: "External model loading", status: "future" as const },
  { name: "HuggingFace compatibility", status: "future" as const },
] as const;

export const NAV_LINKS = [
  { href: "/architecture", label: "Architecture" },
  { href: "/model", label: "Model" },
  { href: "/implementation", label: "Implementation" },
  { href: "/roadmap", label: "Roadmap" },
  { href: "/docs", label: "Docs" },
] as const;
